name = "M 121 Create"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bfed94aba181c8160975b9d32ef0753c1e786d9ef396475b67b849cfa856dbd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
