name = "M 121 Create"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66809d9b665d2986820bb3aabfa5543d811468296d789d9a47dd2be1be1ae86a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
