name = "M 121 Create"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f1b36348e650dc0572b20859183be6a5dc502a9b4edfdfd9f045fc162fb3529"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
